---
collections:
  # - name: ansible.platform

  # - name: ansible.hub
  # - name: ansible.controller
  # - name: ansible.eda
  - name: infra.aap_configuration
  - name: ansible.scm
  - name: community.general
