---
- name: Configure Automation Controller
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  # vars:
  #   controller_configuration_instance_groups_enforce_defaults: true
  #   controller_configuration_credentials_secure_logging: false
  vars:
    # aap_hostname:
    # aap_username: 
    # aap_password: 

  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ controller_configs_dir | default('./configs') }}"
        extensions: ["yaml"]
      tags:
        - always

    - name: Create dummy lighspeed_playbook
      ansible.builtin.include_tasks: dummy_pr.yml

    - name: Project Sync
      ansible.controller.project_update:
        name: Lightspeed-Playbooks
        organization: 'Default'
        controller_host: "{{ aap_hostname }}"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        wait: true
        timeout: 120

    - name: Call all roles
      ansible.builtin.include_role:
        # name: infra.controller_configuration.dispatch
        name: infra.aap_configuration.dispatch


