---
controller_credential_types:
  - name: "ServiceNow"
    description: !unsafe ''
    kind: "cloud"
    inputs:
      fields:
      - id: instance
        type: string
        label: Instance
      - id: username
        type: string
        label: Username
      - id: password
        type: string
        label: Password
        secret: true
      required:
      - instance
      - username
      - password

    injectors:
      env:
        SN_HOST: !unsafe '{{instance}}'
        SN_PASSWORD: !unsafe '{{password}}'
        SN_USERNAME: !unsafe '{{username}}'
...
