---
controller_workflows:
  - name: "AIOps Auto Healing"
    description: !unsafe ''
    organization: "Default"
    simplified_workflow_nodes:

      - identifier: "Apache Service Status Check"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "⚙️ Apache Service Status Check"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "RHEL AI - Analyze Incident"
      - identifier: "RHEL AI - Analyze Incident"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "🤖 RHEL AI: Analyze Incident"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Notify via Mattermost"
      - identifier: "Notify via Mattermost"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "📣 Notify via Mattermost"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Lightspeed Remediation Playbook Generator"
      - identifier: "Lightspeed Remediation Playbook Generator"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "🧠 Lightspeed Remediation Playbook Generator"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Raise Change Request"
      - identifier: "Raise Change Request"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "Raise Change Request"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Commit Fix to Gitea"
      - identifier: "Commit Fix to Gitea"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "🧾 Commit Fix to Gitea"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Sync Playbooks"
      - identifier: "Sync Playbooks"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "Lightspeed-Playbooks"
        limit: ""
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - "Remediate"
      - identifier: "Remediate"
        workflow_job_template: "AIOps Auto Healing"
        unified_job_template: "🔧✅ Execute HTTPD Remediation"
        limit: "node1"
        organization: "Default"
        all_parents_must_converge: "False"


    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    limit: "node1"
    ask_limit_on_launch: false
    ask_inventory_on_launch: false
    webhook_service: ""
    extra_vars: ""
    survey_enabled: true
    survey_spec:
      name: ""
      spec:
        - max: 1024
          min: 0
          type: text
          default: !unsafe "For all hosts, use become true,  Remove line that contains InvalidDirectiveHere from /etc/httpd/conf/httpd.conf and restart httpd"
          required: False
          variable: lightspeed_prompt
          new_question: False
          question_name: !unsafe "LightSpeed Prompt"
      description: ""

