---
controller_templates:
  
  - name: "Raise Change Request"
    description: !unsafe ''
    organization: "Default"
    project: "AAP AIOPS"
    inventory: "Demo Inventory"
    playbook: "playbooks/snow_create_cr_wait_mm.yml"
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - "Demo Credential"
      - "SNOW"
    allow_simultaneous: false
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_limit_on_launch: false
    ask_credential_on_launch: false
    ask_execution_environment_on_launch: false
    ask_labels_on_launch: false
    ask_forks_on_launch: false
    ask_job_slice_count_on_launch: false
    ask_timeout_on_launch: false
    ask_instance_groups_on_launch: false
    extra_vars:
      mattermost_instance: "{{ mattermost_instance }}"
      mattermost_token: "{{ mattermost_token }}"
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    custom_virtualenv: ""
    host_config_key: ""
    survey_enabled: true
    survey_spec:
      name: ""
      spec:
        - max: 1024
          min: 0
          type: text
          required: True
          variable: lightspeed_playbook
          new_question: True
          question_name: !unsafe "Lightspeed Playbook"
      description: ""
    become_enabled: false
    diff_mode: false
    webhook_service: ""
    prevent_instance_group_fallback: false

  - name: "🧠 Lightspeed Remediation Playbook Generator"
    description: !unsafe ''
    organization: "Default"
    project: "AI-EDA"
    inventory: "Demo Inventory"
    playbook: "playbooks/lightspeed_generate.yml"
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - "AAP"
      - "ansible-vault"
    allow_simultaneous: false
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_limit_on_launch: false
    ask_credential_on_launch: false
    ask_execution_environment_on_launch: false
    ask_labels_on_launch: false
    ask_forks_on_launch: false
    ask_job_slice_count_on_launch: false
    ask_timeout_on_launch: false
    ask_instance_groups_on_launch: false
    extra_vars: ""
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    custom_virtualenv: ""
    host_config_key: ""
    survey_enabled: false
    become_enabled: false
    diff_mode: false
    webhook_service: ""
    prevent_instance_group_fallback: false

  - name: "🔧✅ Execute HTTPD Remediation"
    description: !unsafe ''
    organization: "Default"
    project: "Lightspeed-Playbooks"
    inventory: "lab-inventory"
    playbook: "lightspeed-response.yml"
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: "run"
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - "lab-credential"
    allow_simultaneous: false
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: false
    ask_inventory_on_launch: false
    ask_limit_on_launch: true
    ask_credential_on_launch: false
    ask_execution_environment_on_launch: false
    ask_labels_on_launch: false
    ask_forks_on_launch: false
    ask_job_slice_count_on_launch: false
    ask_timeout_on_launch: false
    ask_instance_groups_on_launch: false
    extra_vars: ""
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    custom_virtualenv: ""
    host_config_key: ""
    survey_enabled: false
    become_enabled: true
    diff_mode: false
    webhook_service: ""
    prevent_instance_group_fallback: false