---
controller_credentials:
  - name: "SNOW"
    description: !unsafe ''
    credential_type: "ServiceNow"
    organization: "Default"
    inputs:
      instance: "{{ snow_instance }}"
      password: "{{ snow_password }}"
      username: "{{ snow_username }}"
