---
controller_projects:
  - name: "AAP AIOPS"
    description: !unsafe ''
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/sonstar2/aap-aiops.git"
    scm_branch: ""
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: false
    scm_update_cache_timeout: "0"
    scm_refspec: ""
    allow_override: false
    update_project: false
    timeout: "0"
