---
controller_credentials:
  - name: "SNOW"
    description: !unsafe ''
    credential_type: "ServiceNow"
    organization: "Default"
    inputs:
      instance: 'Change Me'
      password: ''
      username: admin
